package reseptihaku.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import reseptihaku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.02.21 14:41:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsiotTest {



  // Generated by ComTest BEGIN
  /** testSetTiedostoNimi57 */
  @Test
  public void testSetTiedostoNimi57() {    // Osiot: 57
    Osiot osiot = new Osiot(); 
    assertEquals("From: Osiot line: 59", "0|resepti_osiot.dat", osiot.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa110 */
  @Test
  public void testLisaa110() {    // Osiot: 110
    Osiot osiot = new Osiot(); 
    assertEquals("From: Osiot line: 112", "0|resepti_osiot.dat", osiot.toString()); 
    Osio pizzapohja = osiot.lisaa("Pizzapohja"); 
    assertEquals("From: Osiot line: 114", "1|resepti_osiot.dat", osiot.toString()); 
    assertEquals("From: Osiot line: 115", "-1|Pizzapohja", pizzapohja.toString()); 
    Osio tomaattikastike = osiot.lisaa("Tomaattikastike"); 
    assertEquals("From: Osiot line: 118", "2|resepti_osiot.dat", osiot.toString()); 
    assertEquals("From: Osiot line: 119", "-1|Tomaattikastike", tomaattikastike.toString()); 
    Osio taytteet = osiot.lisaa("Täytteet"); 
    assertEquals("From: Osiot line: 122", "3|resepti_osiot.dat", osiot.toString()); 
    assertEquals("From: Osiot line: 123", "-1|Täytteet", taytteet.toString()); 
    osiot.lisaa("Täytteet (vaihtoehto 2)"); 
    assertEquals("From: Osiot line: 126", "4|resepti_osiot.dat", osiot.toString()); 
    osiot.lisaa("Täytteet (vaihtoehto 3)"); 
    assertEquals("From: Osiot line: 129", "5|resepti_osiot.dat", osiot.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa146 */
  @Test
  public void testLisaa146() {    // Osiot: 146
    Osiot osiot = new Osiot(); 
    assertEquals("From: Osiot line: 148", "0|resepti_osiot.dat", osiot.toString()); 
    Osio kastike = new Osio("Kastike"); 
    osiot.lisaa(kastike); 
    assertEquals("From: Osiot line: 152", "1|resepti_osiot.dat", osiot.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista179 */
  @Test
  public void testPoista179() {    // Osiot: 179
    Osiot osiot = new Osiot(); 
    osiot.lisaa("Pohja"); 
    Osio tayte = new Osio("Täyte"); 
    osiot.lisaa(tayte); 
    osiot.lisaa("Kuorrute"); 
    assertEquals("From: Osiot line: 185", "3|resepti_osiot.dat", osiot.toString()); 
    osiot.poista(tayte); 
    assertEquals("From: Osiot line: 188", "2|resepti_osiot.dat", osiot.toString()); 
    osiot.poista(tayte); 
    assertEquals("From: Osiot line: 191", "2|resepti_osiot.dat", osiot.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone355 */
  @Test
  public void testClone355() {    // Osiot: 355
    Osiot osiot = new Osiot(); 
    osiot.setTiedostoNimi("pizza_osiot.txt"); 
    osiot.lisaa(new Osio("Pizzapohja")); 
    osiot.lisaa(new Osio("Tomaattikastike")); 
    osiot.lisaa(new Osio("Täytteet")); 
    Osiot kopioOsiot = osiot.clone(); 
    assertEquals("From: Osiot line: 363", true, kopioOsiot.toString().equals(osiot.toString())); 
    assertEquals("From: Osiot line: 365", "Tomaattikastike", osiot.annaIndeksista(1).getNimi()); 
    assertEquals("From: Osiot line: 366", "Tomaattikastike", kopioOsiot.annaIndeksista(1).getNimi()); 
    osiot.annaIndeksista(1).setUusiNimi("Tulinen kastike"); 
    assertEquals("From: Osiot line: 369", "Tulinen kastike", osiot.annaIndeksista(1).getNimi()); 
    assertEquals("From: Osiot line: 370", "Tomaattikastike", kopioOsiot.annaIndeksista(1).getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals391 */
  @Test
  public void testEquals391() {    // Osiot: 391
    Osiot osiot1 = new Osiot(); 
    Osiot osiot2 = new Osiot(); 
    assertEquals("From: Osiot line: 394", true, osiot1.equals(osiot2)); 
    osiot1.setTiedostoNimi("pizza_osiot.txt"); 
    assertEquals("From: Osiot line: 397", false, osiot1.equals(osiot2)); 
    osiot2.setTiedostoNimi("pizza_osiot.txt"); 
    assertEquals("From: Osiot line: 400", true, osiot1.equals(osiot2)); 
    osiot1.lisaa(new Osio("Pizzapohja")); 
    osiot1.lisaa(new Osio("Tomaattikastike")); 
    assertEquals("From: Osiot line: 404", false, osiot1.equals(osiot2)); 
    osiot2.lisaa(new Osio("Pizzapohja")); 
    osiot2.lisaa(new Osio("Tomaattikastike")); 
    assertEquals("From: Osiot line: 408", true, osiot1.equals(osiot2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHashCode430 */
  @Test
  public void testHashCode430() {    // Osiot: 430
    Osiot osiot1 = new Osiot(); 
    Osiot osiot2 = new Osiot(); 
    assertEquals("From: Osiot line: 433", true, osiot1.hashCode() == osiot2.hashCode()); 
    osiot1.setTiedostoNimi("pizza_osiot.txt"); 
    assertEquals("From: Osiot line: 436", false, osiot1.hashCode() == osiot2.hashCode()); 
    osiot2.setTiedostoNimi("pizza_osiot.txt"); 
    assertEquals("From: Osiot line: 439", true, osiot1.hashCode() == osiot2.hashCode()); 
    osiot1.lisaa(new Osio("Pizzapohja")); 
    osiot1.lisaa(new Osio("Tomaattikastike")); 
    assertEquals("From: Osiot line: 443", false, osiot1.hashCode() == osiot2.hashCode()); 
    osiot2.lisaa(new Osio("Pizzapohja")); 
    osiot2.lisaa(new Osio("Tomaattikastike")); 
    assertEquals("From: Osiot line: 447", true, osiot1.hashCode() == osiot2.hashCode()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString467 */
  @Test
  public void testToString467() {    // Osiot: 467
    Osiot osiot = new Osiot(); 
    assertEquals("From: Osiot line: 469", "0|resepti_osiot.dat", osiot.toString()); 
  } // Generated by ComTest END
}