package reseptihaku.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import reseptihaku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.02.21 14:41:26 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsionAinesosaTest {



  // Generated by ComTest BEGIN
  /** testOsionAinesosa22 */
  @Test
  public void testOsionAinesosa22() {    // OsionAinesosa: 22
    OsionAinesosa oletus = new OsionAinesosa(); 
    assertEquals("From: OsionAinesosa line: 24", "ainesosa|", oletus.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOsionAinesosa39 */
  @Test
  public void testOsionAinesosa39() {    // OsionAinesosa: 39
    OsionAinesosa peruna = new OsionAinesosa("peruna", "1kg"); 
    assertEquals("From: OsionAinesosa line: 41", "peruna|1kg", peruna.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAinesosa56 */
  @Test
  public void testGetAinesosa56() {    // OsionAinesosa: 56
    OsionAinesosa peruna = new OsionAinesosa("peruna", "1kg"); 
    assertEquals("From: OsionAinesosa line: 58", "peruna|1kg", peruna.toString()); 
    assertEquals("From: OsionAinesosa line: 59", "peruna", peruna.getAinesosa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetAinesosa74 */
  @Test
  public void testSetAinesosa74() {    // OsionAinesosa: 74
    OsionAinesosa peruna = new OsionAinesosa("peruna", "1kg"); 
    assertEquals("From: OsionAinesosa line: 76", "peruna|1kg", peruna.toString()); 
    assertEquals("From: OsionAinesosa line: 77", "peruna", peruna.getAinesosa()); 
    peruna.setAinesosa("makkara"); 
    assertEquals("From: OsionAinesosa line: 80", "makkara", peruna.getAinesosa()); 
    peruna.setAinesosa(null); 
    assertEquals("From: OsionAinesosa line: 83", "makkara", peruna.getAinesosa()); 
    peruna.setAinesosa(""); 
    assertEquals("From: OsionAinesosa line: 86", "makkara", peruna.getAinesosa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMaara102 */
  @Test
  public void testGetMaara102() {    // OsionAinesosa: 102
    OsionAinesosa peruna = new OsionAinesosa("peruna", "1kg"); 
    assertEquals("From: OsionAinesosa line: 104", "peruna|1kg", peruna.toString()); 
    assertEquals("From: OsionAinesosa line: 105", "1kg", peruna.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetMaara120 */
  @Test
  public void testSetMaara120() {    // OsionAinesosa: 120
    OsionAinesosa peruna = new OsionAinesosa("peruna", "1kg"); 
    assertEquals("From: OsionAinesosa line: 122", "peruna|1kg", peruna.toString()); 
    assertEquals("From: OsionAinesosa line: 123", "1kg", peruna.getMaara()); 
    peruna.setMaara("2kg"); 
    assertEquals("From: OsionAinesosa line: 126", "2kg", peruna.getMaara()); 
    peruna.setMaara(null); 
    assertEquals("From: OsionAinesosa line: 129", "2kg", peruna.getMaara()); 
    peruna.setMaara(""); 
    assertEquals("From: OsionAinesosa line: 132", "", peruna.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse147 */
  @Test
  public void testParse147() {    // OsionAinesosa: 147
    OsionAinesosa peruna = new OsionAinesosa(); 
    peruna.parse("1|peruna|300g"); 
    assertEquals("From: OsionAinesosa line: 150", "peruna|300g", peruna.toString()); 
    peruna.parse(null); 
    assertEquals("From: OsionAinesosa line: 153", "peruna|300g", peruna.toString()); 
    peruna.parse("  15   |  keltainen peruna    |  1kg     "); 
    assertEquals("From: OsionAinesosa line: 156", "keltainen peruna|1kg", peruna.toString()); 
    peruna.parse("15|peruna 300g"); 
    assertEquals("From: OsionAinesosa line: 159", "peruna 300g|1kg", peruna.toString()); 
    peruna.parse("17 pataatti 280g"); 
    assertEquals("From: OsionAinesosa line: 162", "peruna 300g|1kg", peruna.toString()); 
    peruna.parse("|"); 
    assertEquals("From: OsionAinesosa line: 165", "peruna 300g|1kg", peruna.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone186 */
  @Test
  public void testClone186() {    // OsionAinesosa: 186
    OsionAinesosa juusto = new OsionAinesosa("juusto", "2kg"); 
    assertEquals("From: OsionAinesosa line: 188", "juusto|2kg", juusto.toString()); 
    OsionAinesosa juustoKopio = juusto.clone(); 
    assertEquals("From: OsionAinesosa line: 191", true, juustoKopio.toString().equals(juusto.toString())); 
    juustoKopio.setMaara("3kg"); 
    assertEquals("From: OsionAinesosa line: 194", false, juustoKopio.toString().equals(juusto.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHashCode210 */
  @Test
  public void testHashCode210() {    // OsionAinesosa: 210
    OsionAinesosa juusto1 = new OsionAinesosa("juusto", "2kg"); 
    OsionAinesosa juusto2 = new OsionAinesosa("sinihomejuusto", "2kg"); 
    OsionAinesosa juusto3 = new OsionAinesosa("juusto", "3kg"); 
    assertEquals("From: OsionAinesosa line: 215", false, juusto1.hashCode() == juusto2.hashCode()); 
    assertEquals("From: OsionAinesosa line: 216", false, juusto1.hashCode() == juusto3.hashCode()); 
    assertEquals("From: OsionAinesosa line: 217", false, juusto2.hashCode() == juusto3.hashCode()); 
    juusto3.setMaara("2kg"); 
    assertEquals("From: OsionAinesosa line: 220", true, juusto1.hashCode() == juusto3.hashCode()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals235 */
  @Test
  public void testEquals235() {    // OsionAinesosa: 235
    OsionAinesosa juusto1 = new OsionAinesosa("juusto", "2kg"); 
    OsionAinesosa juusto2 = new OsionAinesosa("sinihomejuusto", "2kg"); 
    OsionAinesosa juusto3 = new OsionAinesosa("juusto", "3kg"); 
    assertEquals("From: OsionAinesosa line: 240", false, juusto1.equals(juusto2)); 
    assertEquals("From: OsionAinesosa line: 241", false, juusto1.equals(juusto3)); 
    assertEquals("From: OsionAinesosa line: 242", false, juusto2.equals(juusto3)); 
    juusto3.setMaara("2kg"); 
    assertEquals("From: OsionAinesosa line: 245", true, juusto1.equals(juusto3)); 
    assertEquals("From: OsionAinesosa line: 246", false, juusto2.equals(juusto3)); 
    assertEquals("From: OsionAinesosa line: 247", true, juusto3.equals(juusto1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString267 */
  @Test
  public void testToString267() {    // OsionAinesosa: 267
    OsionAinesosa mozzarella = new OsionAinesosa("Mozzarella", "120g"); 
    assertEquals("From: OsionAinesosa line: 269", "Mozzarella|120g", mozzarella.toString()); 
  } // Generated by ComTest END
}