package reseptihaku.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import reseptihaku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.02.21 14:41:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsionAinesosatTest {



  // Generated by ComTest BEGIN
  /** testOsionAinesosat40 */
  @Test
  public void testOsionAinesosat40() {    // OsionAinesosat: 40
    OsionAinesosat oletus = new OsionAinesosat(); 
    assertEquals("From: OsionAinesosat line: 42", "-1|osion_ainesosat.dat|0", oletus.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOsionAinesosat56 */
  @Test
  public void testOsionAinesosat56() {    // OsionAinesosat: 56
    OsionAinesosat muropohjaAinesosat = new OsionAinesosat(2); 
    assertEquals("From: OsionAinesosat line: 58", "2|osion_ainesosat.dat|0", muropohjaAinesosat.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa112 */
  @Test
  public void testLisaa112() {    // OsionAinesosat: 112
    OsionAinesosat muropohjaAinesosat = new OsionAinesosat(2); 
    assertEquals("From: OsionAinesosat line: 114", "2|osion_ainesosat.dat|0", muropohjaAinesosat.toString()); 
    muropohjaAinesosat.lisaa(new OsionAinesosa("kananmuna", "2kpl")); 
    muropohjaAinesosat.lisaa(new OsionAinesosa("sokeri", "1dl")); 
    assertEquals("From: OsionAinesosat line: 118", "2|osion_ainesosat.dat|2", muropohjaAinesosat.toString()); 
    assertEquals("From: OsionAinesosat line: 119", "kananmuna", muropohjaAinesosat.anna(0).getAinesosa()); 
    assertEquals("From: OsionAinesosat line: 120", "1dl", muropohjaAinesosat.anna(1).getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna159 */
  @Test
  public void testAnna159() {    // OsionAinesosat: 159
    OsionAinesosat oat = new OsionAinesosat(); 
    assertEquals("From: OsionAinesosat line: 161", true, oat.anna(-5) == null); 
    assertEquals("From: OsionAinesosat line: 162", true, oat.anna(0) == null); 
    oat.lisaa(new OsionAinesosa("Mansikka", "2dl")); 
    assertEquals("From: OsionAinesosat line: 165", "Mansikka", oat.anna(0).getAinesosa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone298 */
  @Test
  public void testClone298() {    // OsionAinesosat: 298
    OsionAinesosat oat = new OsionAinesosat(55); 
    oat.lisaa(new OsionAinesosa("riisi", "5dl")); 
    oat.lisaa(new OsionAinesosa("soijakastike", "2rkl")); 
    OsionAinesosat oatKopio = oat.clone(); 
    assertEquals("From: OsionAinesosat line: 304", true, oat.equals(oatKopio)); 
    assertEquals("From: OsionAinesosat line: 305", "55|osion_ainesosat.dat|2", oat.toString()); 
    oat.lisaa(new OsionAinesosa("sipuli", "1kpl")); 
    assertEquals("From: OsionAinesosat line: 308", false, oat.equals(oatKopio)); 
    oatKopio.lisaa(new OsionAinesosa("sipuli", "1kpl")); 
    assertEquals("From: OsionAinesosat line: 311", true, oat.equals(oatKopio)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals330 */
  @Test
  public void testEquals330() {    // OsionAinesosat: 330
    OsionAinesosat oa1 = new OsionAinesosat(1); 
    OsionAinesosat oa2 = new OsionAinesosat(1); 
    assertEquals("From: OsionAinesosat line: 333", true, oa1.equals(oa2)); 
    oa1.setTiedostoNimi("oa.txt"); 
    assertEquals("From: OsionAinesosat line: 336", false, oa1.equals(oa2)); 
    oa2.setTiedostoNimi("oa.txt"); 
    assertEquals("From: OsionAinesosat line: 339", true, oa1.equals(oa2)); 
    oa1.lisaa(new OsionAinesosa("mustikka", "2dl")); 
    assertEquals("From: OsionAinesosat line: 342", false, oa1.equals(oa2)); 
    oa2.lisaa(new OsionAinesosa("mustikka", "2dl")); 
    assertEquals("From: OsionAinesosat line: 345", true, oa1.equals(oa2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHashCode371 */
  @Test
  public void testHashCode371() {    // OsionAinesosat: 371
    OsionAinesosat oa1 = new OsionAinesosat(1); 
    OsionAinesosat oa2 = new OsionAinesosat(1); 
    assertEquals("From: OsionAinesosat line: 374", true, oa1.hashCode() == oa2.hashCode()); 
    oa1.setTiedostoNimi("oa.txt"); 
    assertEquals("From: OsionAinesosat line: 377", false, oa1.hashCode() == oa2.hashCode()); 
    oa2.setTiedostoNimi("oa.txt"); 
    assertEquals("From: OsionAinesosat line: 380", true, oa1.hashCode() == oa2.hashCode()); 
    oa1.lisaa(new OsionAinesosa("mustikka", "2dl")); 
    assertEquals("From: OsionAinesosat line: 383", false, oa1.hashCode() == oa2.hashCode()); 
    oa2.lisaa(new OsionAinesosa("mustikka", "2dl")); 
    assertEquals("From: OsionAinesosat line: 386", true, oa1.hashCode() == oa2.hashCode()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString409 */
  @Test
  public void testToString409() {    // OsionAinesosat: 409
    OsionAinesosat oa = new OsionAinesosat(1); 
    assertEquals("From: OsionAinesosat line: 411", "1|osion_ainesosat.dat|0", oa.toString()); 
  } // Generated by ComTest END
}