package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.MerkkijonoKasittely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.02.21 14:42:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkijonoKasittelyTest {



  // Generated by ComTest BEGIN
  /** testVaihdaTiedostopaate20 */
  @Test
  public void testVaihdaTiedostopaate20() {    // MerkkijonoKasittely: 20
    assertEquals("From: MerkkijonoKasittely line: 21", "tekstiä.exe", vaihdaTiedostopaate("tekstiä.txt", "exe")); 
    assertEquals("From: MerkkijonoKasittely line: 22", "tekstiä", vaihdaTiedostopaate("tekstiä.txt", "")); 
    assertEquals("From: MerkkijonoKasittely line: 23", "tekstiä", vaihdaTiedostopaate("tekstiä.txt", null)); 
    assertEquals("From: MerkkijonoKasittely line: 24", "tekstiä.exe", vaihdaTiedostopaate("tekstiä", "exe")); 
    assertEquals("From: MerkkijonoKasittely line: 25", "tekstiä..exe", vaihdaTiedostopaate("tekstiä", ".exe")); 
    assertEquals("From: MerkkijonoKasittely line: 26", "tekstiä...exe", vaihdaTiedostopaate("tekstiä", "..exe")); 
    assertEquals("From: MerkkijonoKasittely line: 27", "tekstiä.exe", vaihdaTiedostopaate("     tekstiä   ", "   exe      ")); 
    assertEquals("From: MerkkijonoKasittely line: 28", "tuotteet.tiedot.tekstiä.exe", vaihdaTiedostopaate("tuotteet.tiedot.tekstiä.txt", "exe")); 
    assertEquals("From: MerkkijonoKasittely line: 29", "tekstiä.oma.tiedosto.pääte", vaihdaTiedostopaate("tekstiä.txt", "oma.tiedosto.pääte")); 
    assertEquals("From: MerkkijonoKasittely line: 30", ".exe", vaihdaTiedostopaate("", "exe")); 
    assertEquals("From: MerkkijonoKasittely line: 31", null, vaihdaTiedostopaate(null, "exe")); 
    assertEquals("From: MerkkijonoKasittely line: 32", null, vaihdaTiedostopaate(null, null)); 
    assertEquals("From: MerkkijonoKasittely line: 33", "", vaihdaTiedostopaate("", "")); 
  } // Generated by ComTest END
}