package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.02.21 14:42:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietueHallitsijaTest {



  // Generated by ComTest BEGIN
  /** testTietueHallitsija31 */
  @Test
  public void testTietueHallitsija31() {    // TietueHallitsija: 31
    TietueHallitsija<Object> tietuehallitsija = new TietueHallitsija<Object>(); 
    assertEquals("From: TietueHallitsija line: 33", "0|2.0|0", tietuehallitsija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTietueHallitsija50 */
  @Test
  public void testTietueHallitsija50() {    // TietueHallitsija: 50
    TietueHallitsija<Object> tietueet = new TietueHallitsija<Object>(2.0, 0); 
    assertEquals("From: TietueHallitsija line: 52", "0|2.0|0", tietueet.toString()); 
    tietueet = new TietueHallitsija<Object>(8.0, 5); 
    assertEquals("From: TietueHallitsija line: 55", "0|8.0|5", tietueet.toString()); 
    tietueet = new TietueHallitsija<Object>(-1.5, 100); 
    assertEquals("From: TietueHallitsija line: 58", "0|-1.5|100", tietueet.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaTilaa106 */
  @Test
  public void testLisaaTilaa106() {    // TietueHallitsija: 106
    TietueHallitsija<Object> tietueet = new TietueHallitsija<Object>(2.0, 0); 
    assertEquals("From: TietueHallitsija line: 108", 2, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 109", 4, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 110", 8, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 111", 16, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 112", 32, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 113", 64, tietueet.lisaaTilaa()); 
    tietueet = new TietueHallitsija<Object>(1.0, 2); 
    assertEquals("From: TietueHallitsija line: 116", 3, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 117", 5, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 118", 7, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 119", 9, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 120", 11, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 121", 13, tietueet.lisaaTilaa()); 
    tietueet = new TietueHallitsija<Object>(1.5, 3); 
    assertEquals("From: TietueHallitsija line: 124", 4, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 125", 9, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 126", 16, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 127", 27, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 128", 43, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 129", 67, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 130", 103, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 131", 157, tietueet.lisaaTilaa()); 
    tietueet = new TietueHallitsija<Object>(2, -4); 
    assertEquals("From: TietueHallitsija line: 134", 2, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 135", 3, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 136", 4, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 137", 5, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 138", 6, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 139", 8, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 140", 12, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 141", 20, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 142", 36, tietueet.lisaaTilaa()); 
    assertEquals("From: TietueHallitsija line: 143", 68, tietueet.lisaaTilaa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAdd176 */
  @Test
  public void testAdd176() {    // TietueHallitsija: 176
    TietueHallitsija<Object> olioHallitsija = new TietueHallitsija<Object>(); 
    assertEquals("From: TietueHallitsija line: 178", "0|2.0|0", olioHallitsija.toString()); 
    Object olio = new Object(); 
    olioHallitsija.add(olio); 
    assertEquals("From: TietueHallitsija line: 182", "1|2.0|0", olioHallitsija.toString()); 
    olioHallitsija.add(new Object()); 
    assertEquals("From: TietueHallitsija line: 185", "2|2.0|0", olioHallitsija.toString()); 
    olioHallitsija.add(new Object()); 
    assertEquals("From: TietueHallitsija line: 188", "3|2.0|0", olioHallitsija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRemove205 */
  @Test
  public void testRemove205() {    // TietueHallitsija: 205
    TietueHallitsija<Object> th = new TietueHallitsija<Object>(); 
    th.add(new Object()); 
    th.add(new Object()); 
    assertEquals("From: TietueHallitsija line: 210", "2|2.0|0", th.toString()); 
    assertEquals("From: TietueHallitsija line: 211", 2, th.remove(5)); 
    assertEquals("From: TietueHallitsija line: 212", 2, th.remove(-1)); 
    assertEquals("From: TietueHallitsija line: 213", 1, th.remove(1)); 
    assertEquals("From: TietueHallitsija line: 214", 1, th.remove(1)); 
    assertEquals("From: TietueHallitsija line: 215", 0, th.remove(0)); 
    assertEquals("From: TietueHallitsija line: 216", 0, th.remove(0)); 
    assertEquals("From: TietueHallitsija line: 217", "0|2.0|0", th.toString()); 
    th = new TietueHallitsija<Object>(); 
    assertEquals("From: TietueHallitsija line: 220", "0|2.0|0", th.toString()); 
    th.remove(0); 
    assertEquals("From: TietueHallitsija line: 222", "0|2.0|0", th.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString275 */
  @Test
  public void testToString275() {    // TietueHallitsija: 275
    TietueHallitsija<Object> tietueet = new TietueHallitsija<Object>(); 
    assertEquals("From: TietueHallitsija line: 277", "0|2.0|0", tietueet.toString()); 
    tietueet.add(new Object()); 
    assertEquals("From: TietueHallitsija line: 280", "1|2.0|0", tietueet.toString()); 
    tietueet.add(new Object()); 
    tietueet.add(new Object()); 
    tietueet.add(new Object()); 
    assertEquals("From: TietueHallitsija line: 285", "4|2.0|0", tietueet.toString()); 
  } // Generated by ComTest END
}