package kanta.test;
// Generated by ComTest BEGIN
import java.util.Map;
import java.util.HashMap;
import static org.junit.Assert.*;
import org.junit.*;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.02.21 14:42:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VaihtoehtoAttribuuttiTest {



  // Generated by ComTest BEGIN
  /** testVaihtoehtoAttribuutti34 */
  @Test
  public void testVaihtoehtoAttribuutti34() {    // VaihtoehtoAttribuutti: 34
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 42", "ei määritelty", attribuutti.toString()); 
    attribuutti.setValinta(0); 
    assertEquals("From: VaihtoehtoAttribuutti line: 45", "ei määritelty", attribuutti.toString()); 
    attribuutti.setValinta(1); 
    assertEquals("From: VaihtoehtoAttribuutti line: 48", "vähän", attribuutti.toString()); 
    attribuutti.setValinta(2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 51", "keskimääräisesti", attribuutti.toString()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 54", "paljon", attribuutti.toString()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 57", "paljon", attribuutti.toString()); 
    attribuutti.setValinta(-2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 60", "ei määritelty", attribuutti.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihtoehtoAttribuutti77 */
  @Test
  public void testVaihtoehtoAttribuutti77() {    // VaihtoehtoAttribuutti: 77
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map); 
    assertEquals("From: VaihtoehtoAttribuutti line: 83", "", attribuutti.toString()); 
    attribuutti.setValinta(1); 
    assertEquals("From: VaihtoehtoAttribuutti line: 86", "vähän", attribuutti.toString()); 
    attribuutti.setValinta(2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 89", "keskimääräisesti", attribuutti.toString()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 92", "paljon", attribuutti.toString()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 95", "paljon", attribuutti.toString()); 
    attribuutti.setValinta(-1); 
    assertEquals("From: VaihtoehtoAttribuutti line: 98", "", attribuutti.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetValinta117 */
  @Test
  public void testSetValinta117() {    // VaihtoehtoAttribuutti: 117
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 123", -2, attribuutti.getValinta()); 
    attribuutti.setValinta(0); 
    assertEquals("From: VaihtoehtoAttribuutti line: 126", -2, attribuutti.getValinta()); 
    attribuutti.setValinta(1); 
    assertEquals("From: VaihtoehtoAttribuutti line: 129", 1, attribuutti.getValinta()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 132", 3, attribuutti.getValinta()); 
    attribuutti.setValinta(5); 
    assertEquals("From: VaihtoehtoAttribuutti line: 135", 3, attribuutti.getValinta()); 
    attribuutti.setValinta(-2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 138", -2, attribuutti.getValinta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetValinta159 */
  @Test
  public void testGetValinta159() {    // VaihtoehtoAttribuutti: 159
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 165", -2, attribuutti.getValinta()); 
    attribuutti.setValinta(0); 
    assertEquals("From: VaihtoehtoAttribuutti line: 168", -2, attribuutti.getValinta()); 
    attribuutti.setValinta(1); 
    assertEquals("From: VaihtoehtoAttribuutti line: 171", 1, attribuutti.getValinta()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 174", 3, attribuutti.getValinta()); 
    attribuutti.setValinta(5); 
    assertEquals("From: VaihtoehtoAttribuutti line: 177", 3, attribuutti.getValinta()); 
    attribuutti.setValinta(-2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 180", -2, attribuutti.getValinta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoOletusValinta211 */
  @Test
  public void testOnkoOletusValinta211() {    // VaihtoehtoAttribuutti: 211
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 217", false, attribuutti.onkoOletusValinta(-3)); 
    assertEquals("From: VaihtoehtoAttribuutti line: 218", true, attribuutti.onkoOletusValinta(-2)); 
    assertEquals("From: VaihtoehtoAttribuutti line: 219", false, attribuutti.onkoOletusValinta(-1)); 
    assertEquals("From: VaihtoehtoAttribuutti line: 220", false, attribuutti.onkoOletusValinta(0)); 
    assertEquals("From: VaihtoehtoAttribuutti line: 221", false, attribuutti.onkoOletusValinta(1)); 
    assertEquals("From: VaihtoehtoAttribuutti line: 222", false, attribuutti.onkoOletusValinta(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetValintaString236 */
  @Test
  public void testGetValintaString236() {    // VaihtoehtoAttribuutti: 236
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 242", "ei määritelty", attribuutti.getValintaString()); 
    attribuutti.setValinta(2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 245", "keskimääräisesti", attribuutti.getValintaString()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 248", "paljon", attribuutti.getValintaString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetOletus263 */
  @Test
  public void testGetOletus263() {    // VaihtoehtoAttribuutti: 263
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 269", -2, attribuutti.getOletus()); 
    attribuutti.setValinta(3); 
    assertEquals("From: VaihtoehtoAttribuutti line: 272", -2, attribuutti.getOletus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetOletusString286 */
  @Test
  public void testGetOletusString286() {    // VaihtoehtoAttribuutti: 286
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 292", "ei määritelty", attribuutti.getOletusString()); 
    attribuutti.setValinta(2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 295", "ei määritelty", attribuutti.getOletusString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoNimi377 */
  @Test
  public void testOnkoNimi377() {    // VaihtoehtoAttribuutti: 377
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("Määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 384", "Määrä", attribuutti.getNimi()); 
    assertEquals("From: VaihtoehtoAttribuutti line: 385", false, attribuutti.onkoNimi("hinta")); 
    assertEquals("From: VaihtoehtoAttribuutti line: 386", true, attribuutti.onkoNimi("Määrä")); 
    assertEquals("From: VaihtoehtoAttribuutti line: 387", true, attribuutti.onkoNimi("MÄÄRÄ")); 
    assertEquals("From: VaihtoehtoAttribuutti line: 388", true, attribuutti.onkoNimi("määrä")); 
    assertEquals("From: VaihtoehtoAttribuutti line: 389", false, attribuutti.onkoNimi("")); 
    assertEquals("From: VaihtoehtoAttribuutti line: 390", false, attribuutti.onkoNimi(null)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString404 */
  @Test
  public void testToString404() {    // VaihtoehtoAttribuutti: 404
    Map<Integer, String> map = new HashMap<Integer, String>(); 
    map.put(new Integer(1), new String("vähän")); 
    map.put(new Integer(2), new String("keskimääräisesti")); 
    map.put(new Integer(3), new String("paljon")); 
    VaihtoehtoAttribuutti attribuutti = new VaihtoehtoAttribuutti("määrä", map, -2, "ei määritelty"); 
    assertEquals("From: VaihtoehtoAttribuutti line: 410", "ei määritelty", attribuutti.toString()); 
    attribuutti.setValinta(2); 
    assertEquals("From: VaihtoehtoAttribuutti line: 413", "keskimääräisesti", attribuutti.toString()); 
  } // Generated by ComTest END
}